import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink } from "@/components/ui/navigation-menu";
import { Footer } from "@/components/ui/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/theme-toggle";
import { Navbar } from "@/components/ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-cn" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 明暗主题自适应 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {/* 导航栏 */}
          <div className="pt-4">
            <Navbar />
          </div>

          {/* 主题切换按钮 - 固定在右上角 */}
          <div className="fixed top-5 right-5 z-50">
            <ModeToggle />
          </div>

          {/* 主要内容区域，添加顶部间距避免被导航栏遮挡 */}
          <div className="pt-5 min-h-screen flex flex-col">
            <main className="flex-1">
              {children}
            </main>
          </div>

          {/* 页脚 */}
          <Footer />

        </ThemeProvider>
      </body>
    </html>
  );
}
