import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink } from "@/components/ui/navigation-menu";
import { Footer } from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-cn">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 悬浮导航栏 */}
        <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50">
          <NavigationMenu className="bg-white/80 backdrop-blur-md border border-gray-200 rounded-lg px-6 py-1 shadow-lg dark:bg-black/80 dark:border-gray-800">
            <NavigationMenuList className="flex space-x-6">
              {[
                { href: "/", label: "首页"},
                { href: "/blogs", label: "博客" },
                { href: "/about", label: "关于" }
              ].map(({ href, label }) => (
                <NavigationMenuItem key={href}>
                  <NavigationMenuLink 
                    href={href}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 hover:text-black transition-colors dark:text-gray-300 dark:hover:text-white"
                  >
                    {label}
                  </NavigationMenuLink>
                </NavigationMenuItem>
              ))}
            </NavigationMenuList>
          </NavigationMenu>
        </div>
        
        {/* 主要内容区域，添加顶部间距避免被导航栏遮挡 */}
        <div className="pt-20 min-h-screen flex flex-col">
          <main className="flex-1">
            {children}
          </main>
          
          {/* 页脚 */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
